# Generated by Django 4.0.4 on 2022-04-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('director', models.CharField(default=None, max_length=200, null=True)),
                ('cast', models.TextField()),
                ('release_year', models.IntegerField()),
            ],
        ),
    ]
